# Generated by Django 4.1.3 on 2022-11-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
